apiVersion: v1
kind: Service

metadata:
  name: attendance-management

spec:
  type: NodePort

  selector:
    app: attendance-management

  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 31563